# Generated by Django 5.1.1 on 2024-09-12 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(default='b7f69b820a7b4e8292bc8b54db803a6a', max_length=255, unique=True)),
                ('description', models.TextField()),
                ('pdf_path', models.FileField(upload_to='job_pdfs/')),
                ('unique_link', models.URLField(blank=True, max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AppliedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(default='94f09cf894e549f38c45a9f759da16d7', max_length=255, unique=True)),
                ('resume_path', models.FileField(upload_to='resumes/')),
                ('experience_summary', models.TextField()),
                ('email_id', models.EmailField(max_length=254)),
                ('contact_no', models.CharField(max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portals.job')),
            ],
        ),
    ]
