# Generated by Django 5.1.1 on 2024-09-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedjob',
            name='application_id',
            field=models.CharField(default='b8989dcafdca446299702738cb5535f0', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_id',
            field=models.CharField(default='bac94ed4e50c4bc18ff321e0172bd8a9', max_length=255, unique=True),
        ),
    ]
