# Generated by Django 5.1.1 on 2024-09-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0002_alter_appliedjob_application_id_alter_job_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedjob',
            name='application_id',
            field=models.CharField(default='3c83cf9726674d138bdeca38752376da', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_id',
            field=models.CharField(default='e36add05b9e2429fac91e5df89cf6f82', max_length=255, unique=True),
        ),
    ]
