# Generated by Django 5.1.1 on 2024-10-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0004_remove_job_job_id_remove_job_pdf_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='contact_no',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='email_id',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='experience_summary',
            field=models.TextField(blank=True),
        ),
    ]
