# Generated by Django 4.2.13 on 2024-06-26 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LOGIN",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("user_type", models.CharField(max_length=255)),
            ],
        ),
    ]
